### ISSUE TITLE
Docs tweak

### ISSUE THREAD

**Issue by amsul** [vkurchatkin/generator-foreach#1]
Thanks for this utility. I was going to do the same but this saved me time :+1:. I'd just suggest a slight tweak in the docs:

> Do use it you need to remember a couple of things:
> - ...
> - use `yield *` before `foreach`;
> - ...

The asterisk (`*`) after the `yield` is not required.. it works like a charm even without it :smile: 

Cheers!

**Comment by vkurchatkin** [comment]
@amsul  You are using this with `co`, aren't you? when you yield generator, `co` wraps it with a thunk, so it works as expected (https://github.com/tj/co#yieldables). Try `examples/basic.js`. If you remove asterisk you'll get just `{}`, which is generator itself.

**Comment by amsul** [comment]
Ah, you’re right about that.. my tests are failing without it. Thanks for the wisdom :pray:
